### PR TITLE
allInputs + true

### PR DESCRIPTION
**Pull request by IrinaSing**
Hello! 

I think the program will work better with some changes. I hope that corrections are correct.

### CODE REVIEW

**Comment by colevandersWands** [comment]
Thanks again @IrinaSing, you should take all the modules twice.  They could use the help

**Comment by IrinaSing** [comment]
@colevandersWands no problem, but what do you mean?

> Thanks again @IrinaSing, you should take all the modules twice. They could use the help

Some updates: there were bugs in logging **guessing-game:**

- the program did not show winner in the alert;
- better "phrase" than "number", because program allows strings and don't test for number.
- mistakes with variable names.

**Comment by colevandersWands** [comment]
I mean it's great having you fix all my mistakes,  the more times you take the class the more you'll catch 👍 

Thanks for spotting the number/phrase. I'd refactored it from a number guessing game to a string guessing game and missed this.

**Comment by IrinaSing** [comment]
@colevandersWands  I hope it is a joke 😄 It is possible that I would fix more if I passed through ALL exercises in modules, but my plan is to finish the class in one go 😃 
Don't you want to check your code?

**Comment by colevandersWands** [comment]
It was a joke, you're on track to finish in one go. There's no good reason for you to repeat.

I do try to check my own code, but I write so much of it and it all looks so similar that mistakes always slip through.  If writing exercises was the only thing on my schedule then I'd be able to catch all the mistakes.  I know that's not ideal but it's the best I got for now

**Comment by IrinaSing** [comment]
@colevandersWands I'm sorry. Hopefully generations of students can catch them all step by step 🦾 It is indeed a useful task.

**Pull request merged**
